repos:
  - repo: https://github.com/sirosen/check-jsonschema
    rev: c4654a7e007c9619a5eb63c39a456572a0fa1851  # frozen: 0.38.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
