name: Setup Bats and Bats libraries
description: A GitHub Action for installing Bats and Bats libraries (support, assert, detik, file)
author: bats-core
branding:
  color: yellow
  icon: command

outputs:
  lib-path:
    description: Bats library search path
    value: ${{ steps.config.outputs.install-path }}

runs:
  using: composite
  steps:
    - name: Define install target
      id: config
      shell: bash
      run: |
        set -eu
        install_path="$HOME/.local/share/bats"
        echo "install-path=$install_path" >> "$GITHUB_OUTPUT"
        echo "BATS_LIB_PATH=$install_path" >> "$GITHUB_ENV"

    - name: Download and install Bats and Bats libraries
      shell: bash
      env:
        INSTALL_PATH: ${{ steps.config.outputs.install-path }}
      run: |
        "$GITHUB_ACTION_PATH/install-bats.sh"

    - name: Add Bats to PATH
      shell: bash
      env:
        INSTALL_PATH: ${{ steps.config.outputs.install-path }}
      run: echo "$INSTALL_PATH/bin" >> "$GITHUB_PATH"
