name: CI
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  local_test_options:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.9.0", "1.11.0", "latest"]
        os: [ ubuntu-22.04, ubuntu-latest, windows-2022, windows-latest, macos-14, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    name: local-options
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bats and Bats libs
        id: setup-bats
        uses: ./
        with:
          bats-version: ${{ matrix.version }}
          support-clean: "false"
          assert-clean: "false"
          detik-install: "true"
          file-install: "true"
      - name: Execute test to check Bats-support
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TMP_PATH: ${{ steps.setup-bats.outputs.tmp-path }}
        run: |
          cd ${TMP_PATH}/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TMP_PATH: ${{ steps.setup-bats.outputs.tmp-path }}
        run: |
          cd ${TMP_PATH}/bats-assert/
          bats test
      - name: Execute example tests
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TMP_PATH: ${{ steps.setup-bats.outputs.tmp-path }}
        run:
          bats -T -p tests
