name: CI
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  local_test:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.8.2", "1.9.0", "1.10.0", "1.11.0", "latest"]
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-latest, windows-2022, windows-latest, macos-12, macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}
    env:
      BATS_LIB_PATH: "/usr/lib"
      TERM: xterm
    name: local
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bats and Bats libs
        uses: ./
        with:
          bats-version: ${{ matrix.version }}
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
      - name: Execute test to check Bats-support
        run: |
          cd /tmp/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        run: |
          cd /tmp/bats-assert/
          bats test
      - name: Execute test to check Bats-detik
        run: |
          cd /tmp/bats-detik/
          bats tests
      - name: Execute test to check Bats-file
        # Currently the bats-file tests are broken
        # in gh runner env
        continue-on-error: true
        run: |
          cd /tmp/bats-file/
          bats test
      - name: Execute example tests
        run:
          bats -T -p tests

  local_test_trigger_cache:
    needs: [local_test]
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.8.2", "1.9.0", "1.10.0", "1.11.0", "latest"]
    runs-on: ubuntu-latest
    env:
      BATS_LIB_PATH: "/usr/lib"
      TERM: xterm
    name: local default cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bats and Bats libs
        uses: ./
        with:
          bats-version: ${{ matrix.version }}
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
      - name: Execute test to check Bats-support
        run: |
          cd /tmp/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        run: |
          cd /tmp/bats-assert/
          bats test
      - name: Execute test to check Bats-detik
        run: |
          cd /tmp/bats-detik/
          bats tests
      - name: Execute test to check Bats-file
        # Currently the bats-file tests are broken
        # in gh runner env
        continue-on-error: true
        run: |
          cd /tmp/bats-file/
          bats test
